name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: BENxcoder
          template: classic
          base: header, activity, repositories
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_activity: yes
          plugin_lines: yes
          
